title:              Cristiano Pizzamiglio
email:              cristianopizzamiglio@gmail.com
description:
author:             Cristiano Pizzamiglio
baseurl:            ""
url:                "https://cristianopizzamiglio.github.io"

# Social Profiles
twitter_username:
github_username:    CristianoPizzamiglio
facebook_username:
instagram_username:
linkedin_username:  cristiano-pizzamiglio
youtube_username:   cristiano.pizzamiglio

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           20
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-scholar

collections:
  projects:
    output: true
  philanthropy:
    output: true
highlighter: rouge

scholar:
  style: apa
  details_link: bib.html
  citation_link: true
  in_text_cite:
    suppress_parens: true
